name: Kazuhiko Nakane
description: "I'm Kazu, an Engineering Physics student at UBC"
url: "https://KazuoCalvin.github.io"
baseurl: ""

avatar: https://github.com/KazuoCalvin.png

email: kazuhiko.nakane@gmail.com


remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge


# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - command.txt
  - todo.txt
  - _temp/index.html
  - _temp/
