title: Kazuhiko Nakane
description: "I'm Kazu, an Engineering Physics student at UBC"
url: "https://KazuoCalvin.github.io"
baseurl: ""

author:
  name: Kazu Nakane
  bio: Engineering Physics @ UBC
  avatar: assets/images/avatar.jpg
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/KazuoCalvin"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:kazuhiko.nakane@gmail.com"


remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

mathjax: true

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

permalink: pretty


# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
