name: Kazuhiko Nakane
description: "I'm Kazu, an Engineering Physics student at UBC
  Physics, Condensed Matter Physics, Computational Physics"
url: "https://KazuoCalvin.github.io"
baseurl: ""

theme: minima
