title: Kazuhiko Nakane
description: "I'm Kazu, an Engineering Physics student at UBC"
url: "https://KazuoCalvin.github.io"
baseurl: ""
google_site_verification: "lBHat7bGq-MldLr1Vjh3FkVlnD3TEK9br8g0s_f8vAU"

author:
  name: Kazu Nakane
  bio: Engineering Physics @ UBC
  avatar: /assets/images/Icon_kazu.jpg
  logo: /assets/images/Logo.jpg
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/KazuoCalvin"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:kazuhiko.nakane@gmail.com"

# Theme settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: mint

#plugins
plugins:
  - jekyll-include-cache

#LaTeX
mathjax: true

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

permalink: pretty

# set default

defaults:
  - scope:
      path: ""
    values:
      classes: wide
      author_profile: true


# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
